import { css } from "styled-system/css";

export const markdownMermaidStyles = {
  mermaid: css({
    my: 0,
    px: 4,
    py: 3,
    bg: "bg.default",
    borderTopWidth: "1px",
    borderTopColor: "border.default",
    overflowX: "auto",
    "& svg": {
      display: "block",
      maxW: "100%",
      h: "auto",
      mx: "auto",
    },
  }),
  mermaidError: css({
    px: 4,
    py: 2,
    color: "red.surface.fg",
    bg: "red.surface.bg",
    borderTopWidth: "1px",
    borderTopColor: "red.surface.border",
    fontSize: "sm",
  }),
  mermaidDialogContent: css({
    w: "min(95vw, 1280px)",
    maxW: "95vw",
    h: "min(90dvh, 900px)",
    maxH: "90dvh",
    borderWidth: "1px",
    borderColor: "border.subtle",
    bg: "bg.default",
  }),
  mermaidDialogHeader: css({
    position: "sticky",
    top: 0,
    zIndex: 2,
    pb: 3,
    borderBottomWidth: "1px",
    borderBottomColor: "border.subtle",
    bg: "bg.default",
    backdropFilter: "blur(6px)",
  }),
  mermaidDialogHeaderTop: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 3,
  }),
  mermaidDialogHeaderActions: css({
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  }),
  mermaidDialogDescription: css({
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontSize: "xs",
    color: "fg.muted",
  }),
  mermaidDialogBody: css({
    p: 0,
    h: "100%",
  }),
  mermaidDialogViewport: css({
    position: "relative",
    h: "calc(90dvh - 130px)",
    minH: "420px",
    w: "100%",
    overflow: "hidden",
    bg: "bg.default",
    touchAction: "none",
    cursor: "grab",
  }),
  mermaidDialogCanvas: css({
    position: "relative",
    h: "100%",
    w: "100%",
  }),
  mermaidDialogPanZoom: css({
    position: "absolute",
    left: "50%",
    top: "50%",
    transformOrigin: "center center",
    willChange: "transform",
    "& svg": {
      display: "block",
      maxW: "none",
      h: "auto",
      pointerEvents: "none",
      userSelect: "none",
    },
  }),
};
