import { css } from "styled-system/css";

export const CODE_BLOCK_COLLAPSED_HEIGHT = 240;

export const markdownCodeStyles = {
  preWrapper: css({
    position: "relative",
    my: 4,
    borderRadius: "md",
    overflow: "visible",
    "&:hover [data-code-action='true']": {
      opacity: 1,
      pointerEvents: "auto",
      transform: "translate(0, 0)",
    },
    "&:focus-within [data-code-action='true']": {
      opacity: 1,
      pointerEvents: "auto",
      transform: "translate(0, 0)",
    },
  }),
  codeActionTray: css({
    position: "absolute",
    top: 0,
    right: "8px",
    transform: "translate(0, -30%)",
    zIndex: 3,
    display: "inline-flex",
    alignItems: "center",
    gap: "1",
  }),
  pre: css({
    fontFamily: "mono",
    bg: "bg.subtle",
    borderRadius: "md",
    overflow: "auto",
    p: 4,
    m: 0,
  }),
  preCollapsed: css({
    maxHeight: `${CODE_BLOCK_COLLAPSED_HEIGHT}px`,
    overflow: "hidden",
  }),
  copyButton: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "1",
    borderWidth: "1px",
    borderColor: "border.default",
    bg: "bg.default",
    color: "fg.default",
    borderRadius: "sm",
    px: "2",
    py: "1",
    fontSize: "xs",
    cursor: "pointer",
    opacity: 0,
    pointerEvents: "none",
    transition: "opacity 140ms ease, transform 140ms ease",
    _hover: { bg: "bg.subtle" },
  }),
  expandIconButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: "1px",
    borderColor: "border.default",
    bg: "bg.default",
    color: "fg.default",
    borderRadius: "sm",
    width: "7",
    height: "7",
    cursor: "pointer",
    opacity: 0,
    pointerEvents: "none",
    transition: "opacity 140ms ease, transform 140ms ease",
    _hover: { bg: "bg.subtle" },
  }),
  fadeOverlay: css({
    position: "absolute",
    bottom: "28px",
    left: 0,
    right: 0,
    height: "40px",
    background:
      "linear-gradient(to bottom, transparent 0%, token(colors.bg.subtle) 100%)",
    pointerEvents: "none",
  }),
  expandButton: css({
    width: "100%",
    py: 1.5,
    px: 4,
    bg: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: "xs",
    color: "fg.muted",
    textAlign: "center",
    fontFamily: "sans",
    _hover: {
      color: "fg.default",
      textDecoration: "underline",
    },
  }),
  inlineCode: css({
    fontFamily: "mono",
    bg: "bg.subtle",
    px: 1.5,
    py: 0.5,
    borderRadius: "sm",
    fontSize: "sm",
  }),
  blockCode: css({
    "--md-code-line-digits": "2",
    "--md-code-line-gap": "0.5rem",
    "--md-code-line-column":
      "calc(var(--md-code-line-digits) * 0.72ch + 0.85rem)",
    fontFamily: "mono",
    fontSize: "sm",
    lineHeight: "relaxed",
    display: "block",
    "& .code-line": {
      display: "block",
      paddingLeft: "calc(var(--md-code-line-column) + var(--md-code-line-gap))",
      position: "relative",
      minHeight: "1.4em",
      whiteSpace: "pre",
    },
    "& .code-line::before": {
      content: "attr(data-line)",
      position: "absolute",
      left: 0,
      width: "var(--md-code-line-column)",
      textAlign: "right",
      color: "fg.muted",
      userSelect: "none",
    },
  }),
  codeDrawerContent: css({
    maxW: { base: "100vw", md: "min(92vw, 88ch)" },
    h: "100dvh",
    borderLeftWidth: "1px",
    borderLeftColor: "border.subtle",
    bg: "bg.default",
  }),
  codeDrawerHeader: css({
    position: "sticky",
    top: 0,
    zIndex: 2,
    pb: 3,
    borderBottomWidth: "1px",
    borderBottomColor: "border.subtle",
    bg: "bg.default",
    backdropFilter: "blur(6px)",
  }),
  codeDrawerHeaderTop: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 3,
  }),
  codeDrawerHeaderActions: css({
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
  }),
  codeDrawerDescription: css({
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontSize: "xs",
    color: "fg.muted",
  }),
  codeDrawerBody: css({
    p: 0,
    bg: "bg.default",
    overflow: "auto",
  }),
  codeDrawerScroll: css({
    h: "calc(100dvh - 110px)",
    w: "100%",
    overflow: "auto",
  }),
  codeDrawerPre: css({
    m: 0,
    px: { base: 4, md: 6 },
    py: { base: 4, md: 5 },
    bg: "gray.2",
    minH: "100%",
    overflow: "visible",
  }),
};
